-----------------------------
------CUSTOMER INSERTS-------
-----------------------------
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (6,'49601205811','Aytekin','Çakýcý','Male','28.02.1990','sed@nibh.jp','143 961 5002','Kýrcýlar Mahallesi Ebülfidan Sokak','Gaziantep','12650','B','30.03.2015');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (7,'85508038725','Müjdat','Aþýcý','Male','16.06.1969','sodales@eleifend.ie','513 592 8867','Þehit Komiser Yardýmcýsý Halil Paçaman Sokak','Kýrýkkale','66400','A','08.11.2015');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (8,'64855253847','Halil','Azman','Male','02.07.1969','bibendum@consectetur.mg','129 781 2446','Kýncal Sokak','Kayseri','52400','B','06.10.2008');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (9,'12435833874','Tanpýnar','Söylem','Male','10.01.1980','faucibus@at.gp','734 823 9693','Paþahaný Sokak','Tekirdað','41040','C1','14.03.2013');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (10,'40978569011','Daðhan','Ýnkaya','Male','18.08.1994','ipsum@sodales.ki','509 163 1550','70-50. Sokak','Tekirdað','13700','B','03.11.2011');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (11,'96189185782','Uður','Tophan','Male','31.10.1967','odio@condimentum.bg','916 746 7915','Derecik Caddesi','Þýrnak','02600','B','04.11.2018');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (12,'61444050366','Akasya','Yýlmaz','Female','09.08.1992','varius@a.hu','550 450 0310','Camiyaný Ustalar Mevki','Niðde','80900','B','01.05.2011');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (13,'10912244650','Nurettin','Kuran','Male','06.03.2002','Etiam@eu.gq','827 886 0223','7410/1 Sokak','Uþak','15300','A','16.10.2018');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (14,'15710411272','Sibel','Sevil','Female','26.05.1983','auctor@a.an','585 246 8172','Zeren Aralýðý Sokak','Sivas','26600','B','15.11.2018');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (15,'85916109640','Kübra','Uçkan','Female','08.04.2002','tortor@ac.id','577 897 1216','Yomra Sokak','Kocaeli','43030','B','25.03.2007');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (16,'51497263663','Seda','Aydoðdu','Female','03.12.2001','in@a.dk','527 334 7585','Bahçelievler 21. Sokak','Aksaray','58550','B','19.08.2020');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (17,'48896681921','Cem','Baðcý','Male','24.10.1992','malesuada@mi.ci','462 824 6317','Þehit Emre Urhan Bulvarý','Çankýrý','35472','B','19.04.2017');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (18,'42324667911','Þaheser','Aypiri','Female','02.08.2000','ac@rutrum.pe','555 686 3708','Aðartýr Çýkmazý Sokak','Þanlýurfa','45410','B','08.08.2019');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (19,'86189091125','Candan','Gümüþer','Female','14.12.1999','urna@posuere.st','534 539 0031','Dumlupýnar Mahallesi Maksi Sokak','Mardin','10840','B','17.09.2020');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (20,'50754800177','Dilan','Tekbaþ','Female','20.03.1965','posuere@roin.asia','533 458 7231','Zeytindaðý Mahallesi Ortakla Caddesi No:14','Artvin','43210','B','26.10.2012');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (21,'26702755747','Zehra','Karamýzrak','Female','16.06.1977','nisl@eget.co','541 919 9354','23 Nolu Deniz Sokak','Siirt','48070','B','04.05.2016');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (22,'58544383364','Gülcan','Ekmekçi','Female','04.10.1982','ullamcorper@magna.fo','511 416 1510','Nilüfer Mahallesi Saydað Sokak','Bayburt','42000','B','15.07.2017');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (23,'32597811969','Hayrettin','Mayda','Male','07.03.1959','mollis@lobortis.sj','384 955 5941','92006. Sokak','Tekirdað','57400','B','13.05.2019');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (24,'43690266218','Gülsüm','Katýrcý','Female','13.06.1971','rutrum@Morbi.np','542 119 5617','Mehmet Ali Korkmaz Evleri','Mardin','03110','BE','13.04.2011');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (25,'84892053940','Baran','Sarýbaþ','Male','02.08.1960','Aenean@ut.fi','141 715 4646','Saçlýkasap Caddesi','Sinop','11300','C','26.08.2012');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (26,'26974551078','Pýrýl','Ýmrek','Female','02.04.1964','metus@tempor.pr','537 862 1626','Akyaka Mahallesi Defne Sokak','Iðdýr','75400','BE','11.07.2007'); 
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (27,'32333294240','Ersin','Þener','Male','25.09.1966','condimentum@sagittis.pw','131 294 3339','Yýldýztepe-güzeldere Mevki','Mersin','34394','B','28.01.2018');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (28,'76343392689','Deniz','Çamur','Female','20.03.1989','Proin@eu.ht','563 652 2848','Hunlar Caddesi','Ýstanbul','63570','B','01.02.2009');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (29,'66733012679','Mert','Bakýrcý','Male','02.08.1991','imperdiet@id.ug','408 908 1900','Mýdyat Sokak','Aðrý','33630','B','14.06.2015');
Insert INTO "CAR RENTAL".customers (customer_id, TC_number, name, surname, gender, birth_date, email, phone, address, city, postal_code, license_class, registration_date) values (30,'23753719217','Semih','Solmazgül','Male','11.09.1959','elit@et.gl','729 122 3939','Saylan Mahallesi 156. Sokak','Erzurum','38500','B','08.09.2020');
-------------------
----CAR INSERTS----
-------------------
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (4,'33 L 775','Ford','Bronco','Prestige','4','5','Automatic','Diesel','627,62','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (5,'11 KS 266','Volvo','S90','Prestige','5','5','Automatic', 'Gas','969,57','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (6,'01 EG 114','Toyota','Echo','Economic','5','4','Automatic', 'Diesel','556,40','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (7,'97 CF 548','Land Rover','Discovery','Prestige','5','5','Automatic', 'Gas','894,58','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (8,'60 NO 651','Chevrolet','Tracker','Economic','5','4','Manual', 'Diesel','263,90','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (9,'39 IQ 061','Suzuki','Reno','Economic','5','5','Automatic', 'Diesel','876,52','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (10,'74 ZH 596','Mercedes-Benz','S-Class','Luxury','4','5','Automatic', 'Gas','1402,65','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (11,'24 KG 301','Subaru', 'Forester','Economic','4','5','Manual','Gas','274,24','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (12,'54 MW 170','Mitsubishi','Challenger','Prestige','5','5','Automatic', 'Gas','579,38','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (13,'03 MW 517','Mercury','Grand Marquis','Economic','4','5','Manual', 'Diesel','256,69','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (14,'73 HQ 592','Toyota','Land Cruiser','Prestige','4','4','Automatic', 'Gas','817,43','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (15,'48 TL 799','Chevrolet','Caprice','Economic','4','5','Manual', 'Diesel','477,95','0','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (16,'83 WF 843','Buick','Century','Economic','5','5','Manual', 'Diesel','253,81','0','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (17,'50 WP 173','Oldsmobile','98','Economic','5','5','Manual', 'Diesel','321,63','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values (18,'05 DS 495','Mitsubishi','Eclipse','Economic','4','5','Manual', 'Diesel','312,64','0','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('19','21 QN 053','Pontiac','Grand Prix','Prestige','4','5','Automatic', 'Diesel','658,67','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('20','58 YG 493','Subaru','SVX','Prestige','4','5','Automatic', 'Diesel','545,71','0','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('21','26 YL 184','Subaru','Legacy','Prestige','4','4','Automatic', 'Diesel','779,78','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('22','35 EN 762','Mercury','Cougar','Economic','4','5','Manual', 'Diesel','437,69','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('23','08 KU 323','Chevrolet','Blazer','Prestige','4','5','Automatic', 'Gas','578,77','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('24','70 ZB 621','Acura','RL','Prestige','5','5','Automatic', 'Gas','856,99','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('25','79 OU 966','Subaru','Forester','Economic','5','5','Automatic', 'Diesel','492,66','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('26','47 CD 845','Pontiac','Firebird','Economic','5','4','Manual', 'Diesel','320,01','0','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('27','06 YM 959','Porsche','944','Luxury','4','4','Automatic', 'Gas','1789,61','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('28','03 BZ 464','Ford','Explorer Sport Trac','Prestige','5','4','Automatic', 'Diesel','617,91','0','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('29','33 BW 684','Mitsubishi','Galant','Prestige','5','4','Automatic', 'Diesel','764,93','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('30','77 OY 397','Eagle','Summit','Prestige','4','4','Automatic', 'Gas','959,58','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('31','09 GE 140','Pontiac','Sunfire','Economic','4','5','Automatic', 'Diesel','408,65','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('32','39 WH 237','GMC','Acadia','Economic','5','5','Automatic', 'Diesel','421,25','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('33','57 ZV 110','Dodge','Ram Van B350','Prestige','5','5','Automatic', 'Diesel','726,59','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('34','22 PL 133','GMC','Yukon XL 2500','Economic','5','5','Manual', 'Diesel','330,05','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('35','51 AD 203','Suzuki','XL7','Prestige','5','4','Manual', 'Gas','993,58','0','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('36','15 ZQ 428','Bentley','Arnage','Luxury','4','5','Automatic', 'Gas','1397,35','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('37','85 OB 087','Chevrolet','3500','Prestige','5','5','Automatic', 'Diesel','519,35','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('38','61 WJ 060','Ford','Thunderbird','Prestige','4','5','Automatic', 'Diesel','663,52','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('39','83 QJ 686','Cadillac','SRX','Prestige','4','5','Automatic', 'Gas','580,91','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('40','16 FN 621','BMW','600','Luxury','5','5','Manual', 'Diesel','1271,24','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('41','54 TP 702','Lamborghini','Diablo','Luxury','4','4','Automatic', 'Diesel','1639,21','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('42','98 OL 345','Toyota','Camry','Prestige','5','4','Automatic', 'Diesel','631,77','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('43','37 EE 726','Porsche','911','Luxury','4','4','Automatic', 'Diesel','1422,12','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('44','35 NB 273','Toyota','TundraMax','Prestige','4','4','Automatic', 'Diesel','676,42','0','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('45','91 SB 029','Jaguar','XJ Series','Luxury','5','4','Automatic', 'Diesel','1622,18','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('46','25 DQ 569','Hummer','H1','Economic','4','4','Manual', 'Diesel','420,07','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('47','73 QA 469','Mercedes-Benz','300E','Luxury','5','5','Automatic', 'Gas','1028,93','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('48','66 MR 001','Subaru','Legacy','Economic','4','5','Automatic', 'Diesel','480,94','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('49','82 ZY 155','Mercury','Sable','Prestige','4','5','Automatic', 'Diesel','973,95','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('50','89 FB 174','Ford','Focus','Prestige','4','4','Automatic', 'Gas','825,42','1','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('51','13 LJ 433','Ford','Ranger','Prestige','5','5','Automatic', 'Diesel','614,15','1','0');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('52','86 HC 059','Saturn','Sky','Economic','4','4','Manual', 'Diesel','572,89','0','1');
Insert INTO "CAR RENTAL".cars (car_id, license_plate, car_brand, car_model, class, seat_number, car_door_number, gear_type, fuel_type, daily_price, air_conditioning, availability) values ('53','52 HT 925','Lincoln','Navigator','Prestige','4','4','Automatic', 'Diesel','615,87','0','0');

-----------------------
---BOOKING INSERTS-----
-----------------------
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (4,4,20,'03/11/2015','15/11/2015','19/11/2015');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (5,15,34,'25/03/2007','25/03/2007','01/04/2007');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (6,17,28,'19/04/2017','23/04/2017','24/04/2017');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (7,3,50,'30/12/2014','04/01/2015','11/01/2015');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (8,24,43,'13/04/2011','14/04/2011','17/04/2011');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (9,28,33,'15/02/2009','16/02/2009','21/02/2009');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (10,11,12,'04/11/2018','04/11/2018','06/11/2018');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (11,25,39,'01/09/2012','05/09/2012','10/09/2012');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (12,19,40,'17/09/2020','19/09/2020','25/09/2020');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (13,8,37,'11/10/2008','11/10/2008','16/10/2008');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (14,22,31,'15/11/2017','15/12/2017','02/01/2018');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (15,20,30,'26/10/2014','30/10/2014','03/11/2014');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (16,9,23,'14/05/2013','20/05/2013','27/05/2013');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (17,10,7,'03/11/2011','04/11/2011','09/11/2011');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (18,13,26,'16/10/2018','10/11/2018','10/12/2018');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (19,21,9,'04/05/2016','06/05/2016','10/05/2016');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (20,26,47,'11/07/2007','13/08/2007','17/08/2007');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (21,5,29,'27/03/2019','27/03/2019','29/03/2019');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (22,14,51,'19/11/2018','24/11/2018','03/12/2018');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (23,16,44,'19/08/2020','20/08/2020','22/08/2020');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (24,23,29,'13/06/2019','13/06/2019','20/06/2019');
Insert INTO "CAR RENTAL".bookings (booking_id, customer_id, car_id, booking_date, starting_date, finishing_date) values (25,25,36,'26/08/2013','30/08/2013','04/09/2013');


